### ISSUE TITLE
Add @typedef for options

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#83]
## Description (Motivation)
As "options" param is used in several functions and writing each time 
```js
/**
 * @param {object} [options={random: false,  onlyLetters: false, firstUpper: false, upper: null, lower: null}] Conversion options.
 * @param {boolean} options.random=false - If case conversion should be randomized.
 * @param {boolean} options.onlyLetters=false - If non letters characters should be removed.
 * @param {boolean} options.firstUpper=false - If the first letter should be capitalized instead of the second when converting to mOcKiNgCaSe (e.g. MoCkInGcAsE). When combined with options.random, the first letter of the random string will be capitalized.
 * @param {(string | RegExp)} options.upper=null - Characters or substring set to change to uppercase
 * @param {(string | RegExp)} options.lower=null - Characters or substring set to change to lowercase
*/
```
is not good approach as somewhere it can be missed (forgotten to update), which can lead to confusion in types. 
Creating a typedef and using it where it is needed is the way to go.

## Possible solution
Not sure yet but maybe examples from https://jsdoc.app/tags-typedef.html can help

### TODO:

- [ ] Add `@typedef` for options (problable at the beginning of the file)
- [ ] Replace type of params with new `@typedef` for options
- [ ] Check generated markdown with [jsdoc2md](https://github.com/jsdoc2md/jsdoc-to-markdown) and maybe update README
