### ISSUE TITLE
Add @flowtype for mockingcase

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#85]
## Description (Motivation)
This package has types for TypeScript, jsdoc types and [bindings for ReasonML](https://github.com/strdr4605/bs-mockingcase), maybe adding @flowtype would be a nice idea.

## Possible solution
I think https://flow.org/en/docs/declarations/ is a good point to start, possible types will look like TypeScript ones.

## Expected result
Editors and compilers should correctly use @flowtype for mockingcase

### TODO:

- [ ] Add declaration file for @flowtype
- [ ] Configure usage of flow file in the published version
- [ ] In Pull Request please include a screenshot of usage
